#!/usr/bin/env python3

import json
import os
import pathlib
import subprocess
import time

import click


DIR = pathlib.Path(__file__).absolute().parent
SNAP = pathlib.Path(os.getenv("SNAP") or "/snap/microk8s/current")
SNAP_DATA = pathlib.Path(os.getenv("SNAP_DATA") or "/var/snap/microk8s/current")
SNAP_CURRENT = SNAP_DATA.parent / "current"
SNAP_COMMON = pathlib.Path(os.getenv("SNAP_COMMON") or "/var/snap/microk8s/common")

HELM = SNAP / "microk8s-helm3.wrapper"
MICROK8S_ENABLE = SNAP / "microk8s-enable.wrapper"
CONTAINERD_SOCKET = SNAP_COMMON / "run" / "containerd.sock"
CONTAINERD_TOML = SNAP_CURRENT / "args" / "containerd-template.toml"


def log(msg):
    click.echo(msg, err=True)


@click.command()
@click.option("--backwards-compatible/--no-backwards-compatible", is_flag=True, default=False)
@click.argument(
    "driver-type",
    default="",
    type=click.Choice(["", "force-operator-driver", "force-system-driver"]),
)
@click.option("--requires", multiple=True, default=["core/dns", "core/helm3"])
@click.option("--version", default="v1.10.1")
@click.option("--driver", default="auto", type=click.Choice(["auto", "operator", "host"]))
@click.option("--toolkit-version", default=None)
@click.option(
    "--toolkit-containerd-restart-mode",
    default="signal",
    type=click.Choice(["signal", "none", "manual"]),
)
@click.option("--set-as-default-runtime/--no-set-as-default-runtime", is_flag=True, default=True)
@click.option("--set", "helm_set", multiple=True)
@click.option("-f", "--values", "helm_values", multiple=True, type=click.Path(exists=True))
def main(
    backwards_compatible: bool,
    requires: list,
    version: str,
    driver_type: str,
    driver: str,
    toolkit_version: str,
    toolkit_containerd_restart_mode: str,
    set_as_default_runtime: bool,
    helm_set: list,
    helm_values: list,
):
    if backwards_compatible:
        subprocess.run([DIR / "enable.gpu.sh", driver_type])
        return

    click.echo("Enabling NVIDIA GPU")

    for addon in requires:
        subprocess.run([MICROK8S_ENABLE, addon])

    # handle the deprecated force-operator-driver and force-system-driver options
    if driver_type == "force-operator-driver":
        driver = "operator"
        click.echo(f"WARNING: {driver_type} is deprecated. Please use --driver=operator")
    elif driver_type == "force-system-driver":
        driver = "host"
        click.echo(f"WARNING: {driver_type} is deprecated. Please use --driver=host")
    elif driver == "auto":
        try:
            click.echo("Checking if NVIDIA driver is already installed")
            subprocess.check_call(["nvidia-smi", "-L"])
            driver = "host"
        except OSError:
            driver = "operator"

    click.echo(f"Using {driver} GPU driver")
    helm_args = [
        "install",
        "gpu-operator",
        "nvidia/gpu-operator",
        f"--version={version}",
        "--create-namespace",
        "--namespace=gpu-operator-resources",
        "-f",
        "-",
    ]

    helm_config = {
        "operator": {
            "defaultRuntime": "containerd",
        },
        "driver": {
            "enabled": ("true" if driver == "operator" else "false"),
        },
        "toolkit": {
            "enabled": "true",
            "env": [
                {"name": "CONTAINERD_CONFIG", "value": CONTAINERD_TOML.as_posix()},
                {"name": "CONTAINERD_SOCKET", "value": CONTAINERD_SOCKET.as_posix()},
                {
                    "name": "CONTAINERD_SET_AS_DEFAULT",
                    "value": "1" if set_as_default_runtime else "0",
                },
            ],
        },
    }
    if toolkit_version is not None:
        helm_config["toolkit"]["version"] = toolkit_version
    if toolkit_containerd_restart_mode != "signal":
        helm_config["toolkit"]["env"].extend(
            [
                {"name": "NO_DAEMON", "value": "1"},
                {"name": "CONTAINERD_RESTART_MODE", "value": "none"},
            ]
        )

    for arg in helm_set:
        helm_args.extend(["--set", arg])
    for arg in helm_values:
        helm_args.extend(["--values", arg])

    subprocess.run([HELM, "repo", "add", "nvidia", "https://nvidia.github.io/gpu-operator"])
    subprocess.run([HELM, *helm_args], input=json.dumps(helm_config).encode())

    if toolkit_containerd_restart_mode == "none":
        nvidia_container_runtime = "/usr/local/nvidia/toolkit/bin/nvidia-container-runtime"
        click.echo(
            f"""
===================================================================================

NOTE: You will have to restart containerd manually once the container runtime
has been installed. You can do this with:

    while ! grep "{nvidia_container_runtime}" "{CONTAINERD_TOML}"; do
        echo "Waiting for nvidia-container-runtime"
        sleep 5
    done
    sudo snap restart microk8s.daemon-containerd

"""
        )
    elif toolkit_containerd_restart_mode == "manual":
        for i in range(100):
            click.echo(f"Waiting for nvidia-container-runtime (attempt {i})")
            with open(CONTAINERD_TOML, "r") as fin:
                if "/usr/local/nvidia/toolkit" in fin.read():
                    break
            time.sleep(5)

        click.echo("Restarting containerd to enable nvidia-container-runtime")
        try:
            subprocess.run(["snapctl", "restart", "microk8s.daemon-containerd"])
        except OSError:
            click.echo(
                """
WARNING: Failed to restart containerd. Please restart manually to finish the installation:

sudo snap restart microk8s.daemon-containerd
"""
            )

    click.echo("NVIDIA is enabled")


if __name__ == "__main__":
    main()
